apiVersion: key.garage.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: key/v1alpha1/key
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: my-application-key
