apiVersion: garage.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: garage
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      key: credentials
      name: garage-creds
      namespace: crossplane-system
