// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PermissionInitParameters struct {

	// (String) The ID of the access key.
	// The ID of the access key.
	// +crossplane:generate:reference:type=github.com/eaglesemanation/provider-garage/apis/namespaced/key/v1alpha1.Key
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// Reference to a Key in key to populate accessKeyId.
	// +kubebuilder:validation:Optional
	AccessKeyIDRef *v1.NamespacedReference `json:"accessKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in key to populate accessKeyId.
	// +kubebuilder:validation:Optional
	AccessKeyIDSelector *v1.NamespacedSelector `json:"accessKeyIdSelector,omitempty" tf:"-"`

	// (String) The ID of the bucket.
	// The ID of the bucket.
	// +crossplane:generate:reference:type=github.com/eaglesemanation/provider-garage/apis/namespaced/bucket/v1alpha1.Bucket
	BucketID *string `json:"bucketId,omitempty" tf:"bucket_id,omitempty"`

	// Reference to a Bucket in bucket to populate bucketId.
	// +kubebuilder:validation:Optional
	BucketIDRef *v1.NamespacedReference `json:"bucketIdRef,omitempty" tf:"-"`

	// Selector for a Bucket in bucket to populate bucketId.
	// +kubebuilder:validation:Optional
	BucketIDSelector *v1.NamespacedSelector `json:"bucketIdSelector,omitempty" tf:"-"`

	// (Boolean) Grant owner permission to the access key.
	// Grant owner permission to the access key.
	Owner *bool `json:"owner,omitempty" tf:"owner,omitempty"`

	// (Boolean) Grant read permission to the access key.
	// Grant read permission to the access key.
	Read *bool `json:"read,omitempty" tf:"read,omitempty"`

	// (Boolean) Grant write permission to the access key.
	// Grant write permission to the access key.
	Write *bool `json:"write,omitempty" tf:"write,omitempty"`
}

type PermissionObservation struct {

	// (String) The ID of the access key.
	// The ID of the access key.
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// (String) The ID of the bucket.
	// The ID of the bucket.
	BucketID *string `json:"bucketId,omitempty" tf:"bucket_id,omitempty"`

	// (String) The unique identifier of the permission (format: bucket_id/access_key_id).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Grant owner permission to the access key.
	// Grant owner permission to the access key.
	Owner *bool `json:"owner,omitempty" tf:"owner,omitempty"`

	// (Boolean) Grant read permission to the access key.
	// Grant read permission to the access key.
	Read *bool `json:"read,omitempty" tf:"read,omitempty"`

	// (Boolean) Grant write permission to the access key.
	// Grant write permission to the access key.
	Write *bool `json:"write,omitempty" tf:"write,omitempty"`
}

type PermissionParameters struct {

	// (String) The ID of the access key.
	// The ID of the access key.
	// +crossplane:generate:reference:type=github.com/eaglesemanation/provider-garage/apis/namespaced/key/v1alpha1.Key
	// +kubebuilder:validation:Optional
	AccessKeyID *string `json:"accessKeyId,omitempty" tf:"access_key_id,omitempty"`

	// Reference to a Key in key to populate accessKeyId.
	// +kubebuilder:validation:Optional
	AccessKeyIDRef *v1.NamespacedReference `json:"accessKeyIdRef,omitempty" tf:"-"`

	// Selector for a Key in key to populate accessKeyId.
	// +kubebuilder:validation:Optional
	AccessKeyIDSelector *v1.NamespacedSelector `json:"accessKeyIdSelector,omitempty" tf:"-"`

	// (String) The ID of the bucket.
	// The ID of the bucket.
	// +crossplane:generate:reference:type=github.com/eaglesemanation/provider-garage/apis/namespaced/bucket/v1alpha1.Bucket
	// +kubebuilder:validation:Optional
	BucketID *string `json:"bucketId,omitempty" tf:"bucket_id,omitempty"`

	// Reference to a Bucket in bucket to populate bucketId.
	// +kubebuilder:validation:Optional
	BucketIDRef *v1.NamespacedReference `json:"bucketIdRef,omitempty" tf:"-"`

	// Selector for a Bucket in bucket to populate bucketId.
	// +kubebuilder:validation:Optional
	BucketIDSelector *v1.NamespacedSelector `json:"bucketIdSelector,omitempty" tf:"-"`

	// (Boolean) Grant owner permission to the access key.
	// Grant owner permission to the access key.
	// +kubebuilder:validation:Optional
	Owner *bool `json:"owner,omitempty" tf:"owner,omitempty"`

	// (Boolean) Grant read permission to the access key.
	// Grant read permission to the access key.
	// +kubebuilder:validation:Optional
	Read *bool `json:"read,omitempty" tf:"read,omitempty"`

	// (Boolean) Grant write permission to the access key.
	// Grant write permission to the access key.
	// +kubebuilder:validation:Optional
	Write *bool `json:"write,omitempty" tf:"write,omitempty"`
}

// PermissionSpec defines the desired state of Permission
type PermissionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PermissionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PermissionInitParameters `json:"initProvider,omitempty"`
}

// PermissionStatus defines the observed state of Permission.
type PermissionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PermissionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Permission is the Schema for the Permissions API. Manages permissions for an access key on a Garage S3 bucket.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,garage}
type Permission struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PermissionSpec   `json:"spec"`
	Status            PermissionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PermissionList contains a list of Permissions
type PermissionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Permission `json:"items"`
}

// Repository type metadata.
var (
	Permission_Kind             = "Permission"
	Permission_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Permission_Kind}.String()
	Permission_KindAPIVersion   = Permission_Kind + "." + CRDGroupVersion.String()
	Permission_GroupVersionKind = CRDGroupVersion.WithKind(Permission_Kind)
)

func init() {
	SchemeBuilder.Register(&Permission{}, &PermissionList{})
}
